version: "3.8"

services:
  airflow:
    image: apache/airflow:2.7.3
    container_name: airflow
    restart: always

    environment:
      AIRFLOW__CORE__EXECUTOR: SequentialExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: sqlite:////opt/airflow/airflow.db
      AIRFLOW__CORE__LOAD_EXAMPLES: "false"
      AIRFLOW__CORE__ENABLE_XCOM_PICKLING: "true"
      AIRFLOW_UID: "50000"
      _PIP_ADDITIONAL_REQUIREMENTS: pandas scikit-learn kneed

    ports:
      - "8080:8080"

    volumes:
      - ./dags:/opt/airflow/dags
      - ./plugins:/opt/airflow/plugins
      - ./working_data:/opt/airflow/working_data

    command: >
      bash -c "airflow db migrate &&
      airflow users create --username admin --password admin --firstname Admin --lastname User --role Admin --email admin@example.com &&
      airflow webserver & airflow scheduler"

